The check harnass has been modified so that it now reports how many tests failed at the end of the automatic checks. This reduces the risk of a test failing without being noticed.

diff --git a/test/check.template b/test/check.template
--- a/test/check.template
+++ b/test/check.template
@@ -23,7 +23,7 @@ DIR=`dirname $SCRIPT`
 EXECPATH=$DIR/../bin
 
 # The executable we are using.
-echo "$EXECPATH/$@"
+echo "EXECUTABLE: $EXECPATH/$@"
 # Check that the executable exists.
 if [ ! -f "$EXECPATH/$1" ]
 then
@@ -31,8 +31,10 @@ then
     exit 1
 fi
 
+NUM_FAILURES=0
+
 FILES=`ls -1 *.chk | sed 's/\.[a-z]*\.chk//g' | sort -u`
-echo $FILES
+echo "CHECKING: " $FILES
 for file in $FILES; do
     CHECK_FILES=`ls -1 ${file}.*.chk | egrep "^${file}.[a-z]*.chk" | sed s/\.chk//g`
     rm -f $CHECK_FILES
@@ -44,6 +46,7 @@ for file in $FILES; do
         diff -b -q ${check_file}.chk ${check_file} > /dev/null
         if [ $? != 0 ]; then
             STATUS="FAILED"
+            NUM_FAILURES=$(($NUM_FAILURES+1))
             break
         fi
     done
@@ -51,3 +54,11 @@ for file in $FILES; do
     echo "$TIME"
     rm -f $CHECK_FILES
 done
+
+if [ $NUM_FAILURES == 0 ]; then
+    echo "**** ALL TESTS PASSED! ****"
+else
+    echo "**** $NUM_FAILURES TEST(S) FAILED! ****"
+fi
+# The exit status of this script is the number of tests that failed.
+exit $NUM_FAILURES
diff --git a/test/checkall b/test/checkall
--- a/test/checkall
+++ b/test/checkall
@@ -16,19 +16,33 @@
 # 
 # You should have received a copy of the GNU General Public License
 # along with this program; if not, write to the Free Software
-# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA. 
+# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
+
+if [ $# != 0 ]; then
+    echo "usage: checkall"
+    exit
+fi
 
 CHECKS=`find . -name check`
+
+export NUM_FAILURES=0
 
 for file in $CHECKS
 do
     echo $file
     DIR=`dirname $file`
     (cd $DIR; ./check)
+    NUM_FAILURES=$(($NUM_FAILURES+$?))
 done
 
-if [ $# != 0 ]; then
-    echo "usage: checkall"
-    exit
+echo ""
+echo "***************************"
+if [ $NUM_FAILURES == 0 ]; then
+    echo "**** ALL TESTS PASSED! ****"
+else
+    echo "**** $NUM_FAILURES TEST(S) FAILED! ****"
 fi
+echo "***************************"
+# The exit status of this script is the number of tests that failed.
+exit $NUM_FAILURES
 
diff --git a/test/ppi/check-ppi b/test/ppi/check-ppi
--- a/test/ppi/check-ppi
+++ b/test/ppi/check-ppi
@@ -31,6 +31,8 @@ then
     exit 1
 fi
 
+num_failures=0
+
 FILES=`ls -1 *.chk | sed 's/\.[a-z]*\.chk//g' | sort -u`
 echo $FILES
 for file in $FILES; do
@@ -44,6 +46,7 @@ for file in $FILES; do
         diff -b -q ${check_file}.chk ${check_file} > /dev/null
         if [ $? != 0 ]; then
             STATUS="FAILED"
+            num_failures=$(($num_failures+1))
             break
         fi
     done
@@ -51,3 +54,11 @@ for file in $FILES; do
     echo "$TIME"
     rm -f $CHECK_FILES
 done
+
+if [ $num_failures == 0 ]; then
+    echo "**** All tests PASSED! ****"
+else
+    echo "**** $num_failures test(s) FAILED! ****"
+fi
+# The exit status of this script is the number of tests that failed.
+exit $num_failures
